<?php
 /**
 * GoMage Advanced Navigation Extension
 *
 * @category     Extension
 * @copyright    Copyright (c) 2010-2011 GoMage (http://www.gomage.com)
 * @author       GoMage
 * @license      http://www.gomage.com/license-agreement/  Single domain license
 * @terms of use http://www.gomage.com/terms-of-use
 * @version      Release: 2.0
 * @since        Class available since Release 2.0
 */
?>

<ol <?php if($this->canShowCheckbox()):?>class="gan-list-checkbox"<?php endif;?>>
<?php $_top_level = null; ?>
<?php foreach ($this->getItems() as $_item): ?>
    <?php if (!$_top_level) $_top_level = $_item->getLevel(); ?>      
    <li style="padding-left: <?php echo 10*($_item->getLevel() - $_top_level); ?>px;" >
        <?php if (($_item->getCount() > 0) || $_item->getHasChild() || $_item->getActive()): ?>
        <a <?php if($_item->getActive()):?> class="active" <?php endif;?> <?php if($this->ajaxEnabled()):?> onclick="setNavigationUrl('<?php echo ($_item->getActive() ? $_item->getRemoveUrl(true) : $_item->getUrl(true)) ?>'); return false;" <?php endif;?> href="<?php echo ($_item->getActive() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
        <?php else: echo $_item->getLabel() ?>
        <?php endif; ?>
    	<?php if(!$_item->getActive()):?>
        (<?php echo $_item->getCount() ?>)
        <?php endif;?>
    </li>
<?php endforeach ?>
</ol>
